import { Schema } from "effect";
import { TaskPrioritySchema, TaskStatusSchema } from "./schema";
import { parametersFromSchema, type ToolkitTool } from "../../platform/toolkit/schema";

const EmptyParameters = { type: "object", properties: {}, required: [], additionalProperties: false };
const TaskIdSchema = Schema.Struct({
  id: Schema.String.annotations({ description: "Task id." }),
});
const TaskInputSchema = Schema.Struct({
  title: Schema.String.annotations({ description: "Task title." }),
  notes: Schema.optional(Schema.String.annotations({ description: "Optional task notes." })),
  dueAt: Schema.optional(Schema.String.annotations({ description: "Optional ISO timestamp due date." })),
  priority: Schema.optional(TaskPrioritySchema.annotations({ description: "Task priority." })),
  durationMinutes: Schema.optional(Schema.Number.annotations({ description: "Estimated duration in minutes." })),
  links: Schema.optional(Schema.Array(Schema.String).annotations({ description: "Optional related URLs." })),
  multiSession: Schema.optional(Schema.Boolean.annotations({ description: "Whether the task can have multiple work sessions." })),
  source: Schema.optional(Schema.String.annotations({ description: "Source creating the task, e.g. pi." })),
});
const TaskPatchSchema = Schema.Struct({
  id: Schema.String.annotations({ description: "Task id." }),
  title: Schema.optional(Schema.String.annotations({ description: "Updated task title." })),
  notes: Schema.optional(Schema.String.annotations({ description: "Updated task notes." })),
  dueAt: Schema.optional(Schema.String.annotations({ description: "Updated ISO timestamp due date." })),
  priority: Schema.optional(TaskPrioritySchema.annotations({ description: "Updated task priority." })),
  durationMinutes: Schema.optional(Schema.Number.annotations({ description: "Updated estimated duration in minutes." })),
  links: Schema.optional(Schema.Array(Schema.String).annotations({ description: "Updated related URLs." })),
  multiSession: Schema.optional(Schema.Boolean.annotations({ description: "Whether the task can have multiple work sessions." })),
  status: Schema.optional(TaskStatusSchema.annotations({ description: "Updated task status." })),
});
const TaskSessionCreateSchema = Schema.Struct({
  id: Schema.String.annotations({ description: "Existing task id to schedule." }),
  startAt: Schema.String.annotations({ description: "ISO timestamp session start time." }),
  endAt: Schema.String.annotations({ description: "ISO timestamp session end time." }),
});
const TaskSessionUpdateSchema = Schema.Struct({
  id: Schema.String.annotations({ description: "Existing task session id to update." }),
  startAt: Schema.String.annotations({ description: "Updated ISO timestamp session start time." }),
  endAt: Schema.String.annotations({ description: "Updated ISO timestamp session end time." }),
});

export const taskToolkitTools = [
  {
    id: "task.list",
    name: "anorvis_list_tasks",
    label: "List Tasks",
    description: "List tasks in Anorvis OS.",
    domain: "life",
    operation: "read",
    resource: "task",
    mutates: false,
    method: "GET",
    path: "/v1/tasks",
    parameters: EmptyParameters,
  },
  {
    id: "task.create",
    name: "anorvis_create_task",
    label: "Create Task",
    description: "Create a task in Anorvis OS.",
    domain: "life",
    operation: "create",
    resource: "task",
    mutates: true,
    method: "POST",
    path: "/v1/tasks",
    parameters: parametersFromSchema(TaskInputSchema),
  },
  {
    id: "task.update",
    name: "anorvis_update_task",
    label: "Update Task",
    description: "Update an existing task in Anorvis OS.",
    domain: "life",
    operation: "update",
    resource: "task",
    mutates: true,
    method: "PATCH",
    path: "/v1/tasks/:id",
    pathParams: ["id"],
    parameters: parametersFromSchema(TaskPatchSchema),
  },
  {
    id: "task.complete",
    name: "anorvis_complete_task",
    label: "Complete Task",
    description: "Mark a task complete in Anorvis OS.",
    domain: "life",
    operation: "complete",
    resource: "task",
    mutates: true,
    method: "PATCH",
    path: "/v1/tasks/:id/complete",
    pathParams: ["id"],
    parameters: parametersFromSchema(TaskIdSchema),
  },
  {
    id: "task.delete",
    name: "anorvis_delete_task",
    label: "Delete Task",
    description: "Delete a task from Anorvis OS.",
    domain: "life",
    operation: "delete",
    resource: "task",
    mutates: true,
    method: "DELETE",
    path: "/v1/tasks/:id",
    pathParams: ["id"],
    parameters: parametersFromSchema(TaskIdSchema),
  },
  {
    id: "task_session.create",
    name: "anorvis_create_task_session",
    label: "Create Task Session",
    description: "Create a scheduled task session for an existing task in Anorvis OS.",
    domain: "life",
    operation: "create",
    resource: "task_session",
    mutates: true,
    method: "PATCH",
    path: "/v1/tasks/sessions/:id",
    pathParams: ["id"],
    parameters: parametersFromSchema(TaskSessionCreateSchema),
  },
  {
    id: "task_session.update",
    name: "anorvis_update_task_session",
    label: "Update Task Session",
    description: "Update an existing scheduled task session in Anorvis OS.",
    domain: "life",
    operation: "update",
    resource: "task_session",
    mutates: true,
    method: "PATCH",
    path: "/v1/tasks/sessions/:id",
    pathParams: ["id"],
    parameters: parametersFromSchema(TaskSessionUpdateSchema),
  },
  {
    id: "task_session.list",
    name: "anorvis_list_task_sessions",
    label: "List Task Sessions",
    description: "Task sessions are included in the Life snapshot.",
    domain: "life",
    operation: "read",
    resource: "task_session",
    mutates: false,
    method: "GET",
    path: "/v1/life/snapshot",
    parameters: EmptyParameters,
  },
] satisfies ToolkitTool[];
